/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cli_NetScoreUtil */

#ifndef _Included_cli_NetScoreUtil
#define _Included_cli_NetScoreUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cli_NetScoreUtil
 * Method:    CalculateNetScore
 * Signature: (Ljava/lang/String;)Lcli/NetScoreMetric;
 */
JNIEXPORT jobject JNICALL Java_cli_NetScoreUtil_CalculateNetScore
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
